### PR TITLE
fix: localization and input-handling bug bundle

### LINKED ISSUE #1093: [Bug]: Age Rating Localization Failure (Simple Language Codes)
### Pre-flight checks

- [x] I searched existing issues and this is not a duplicate.
- [x] I can reproduce this on the latest release or latest main build.
- [x] This issue is limited to a single bug (not multiple unrelated problems).

### App version / commit

Beta 0.6.3

### Install method

GitHub Release APK

### Platform

Android TV

### Device model

All

### Android version

12/14

### Player mode

Internal player

### Area (tag)

UI / Layout

### Steps to reproduce

1. Change the application or system language: Set the interface to French (fr).
2. Search for a recent movie: Navigate to the movie page of a film with a known French rating (e.g., Superman 2025 or any released film with a TP (Tous Publics) rating).
3. Observe the metadata: Check the displayed Age Rating badge.

### Expected behavior

The application should correctly identify the region from the ISO language code "fr" and display the local French rating (e.g., TP, 12).

### Actual behavior

The application fails to extract the region from the short ISO code "fr", as the current logic expects a hyphenated string. Since the French region (FR) is missed, the search priority defaults to US and GB, displaying an American rating (e.g., PG-13) instead of the local French one.

### Frequency

Always

### Did this work before?

No, it never worked

### Media details (optional)

Image
Image

### Logs (required for crash reports)

```shell

```

### Anything else? (optional)

1. Problem SummaryThe age rating system fails to identify the user's region when a simple language code is used (e.g., "fr" instead of "fr-FR"). Consequently, the system ignores local maturity ratings (such as -12 or -16 in France) and defaults to American (US) or British (GB) classifications.

2. Technical AnalysisThe malfunction is located within the preferredRegions function:Region Extraction Error: The code uses normalizedLanguage.substringAfter("-", "") to isolate the country code.If the provided language is simply "fr", there is no hyphen. The function returns an empty string.The .takeIf { it.length == 2 } filter rejects this empty string, resulting in a null fromLanguage variable.Priority Impact: Since fromLanguage is null, the generated priority region list consists only of [US, GB]. The region corresponding to the user's actual language is never added to the priority search performed in selectMovieAgeRating.

3. Concrete Example: Superman (2025)To illustrate the issue using the film Superman (2025) for a user configured with the "fr" language:Expected Behavior: The system should identify the France region and display the French classification (e.g., "TP" or "Tous publics").Current Behavior: Because preferredRegions finds no country code for "fr", it triggers a search for US then GB zones. The user sees the American "PG-13" certification despite having a French interface.

4. Test ResultsI attempted to fix the issue by forcing French into the code as a test, but I was unable to resolve the malfunction satisfactorily. The dynamic link between the simple language code and its respective region does not seem to trigger correctly. If someone more experienced could examine the preferredRegions function to stabilize this behavior, it would ensure localization meets expectations.

### LINKED ISSUE #1184: [Bug]: the player needs translation strings for "S" and "E"
### Pre-flight checks

- [x] I searched existing issues and this is not a duplicate.
- [x] I can reproduce this on the latest release or latest main build.
- [x] This issue is limited to a single bug (not multiple unrelated problems).

### App version / commit

0.5.5

### Install method

GitHub Release APK

### Platform

Android TV

### Device model

Homatics 4K R Plus

### Android version

Android 14

### Player mode

Internal player

### Area (tag)

Other

### Steps to reproduce

Also, It needs to follow the same pattern, all "S01E01" without spaces or all "S01 E01" with a space

Play/Pause:

Image

Sources:

Image

Episodes:

Image

### Expected behavior

Should have the translation for other languages

### Actual behavior

Only english (S/E) for now

### Frequency

Always

### Did this work before?

Not sure

### Media details (optional)

_No response_

### Logs (required for crash reports)

```shell

```

### Anything else? (optional)

_No response_

### LINKED ISSUE #1230: [Suggestion]: When sorting the Library alphabetically, ignore the word, 'The'.
### Pre-flight checks

- [x] I searched existing issues and this is not a duplicate.
- [x] I can reproduce this on the latest release or latest main build.
- [x] This issue is limited to a single bug (not multiple unrelated problems).

### App version / commit

0.5.6-beta

### Install method

GitHub Release APK

### Platform

Google TV

### Device model

Google TV Streamer

### Android version

Android 14

### Player mode

Internal player

### Area (tag)

UI / Layout

### Steps to reproduce

- Go to Library
- Sort Alphabetically

### Expected behavior

The whole list should be sorted alphabetically... 

### Actual behavior

...But when 'Sorting / Searching' the Library list alphabetically, the word 'The' essentially has its own 'sub-alphabetized' list because of its second word (which is quite annoying).

I think if an item's name begins with 'The', then it should be ignored, and instead, the second word should be the focus when sorting alphabetically.

### Frequency

Always

### Did this work before?

Not sure

### Media details (optional)

_No response_

### Logs (required for crash reports)

```shell

```

### Anything else? (optional)

_No response_

### LINKED ISSUE #1275: [Bug]: Crash in URL decoder if stream contains illegal characters
### Pre-flight checks

- [x] I searched existing issues and this is not a duplicate.
- [x] I can reproduce this on the latest release or latest main build.
- [x] This issue is limited to a single bug (not multiple unrelated problems).

### App version / commit

0.5.7

### Install method

GitHub Release APK

### Platform

Android TV

### Device model

HiSense 

### Android version

12

### Player mode

Internal player

### Area (tag)

Playback (start/stop/buffering)

### Steps to reproduce

1. Open any movie where the stream description has a % in it and try to play it
2. Immediate crash

### Expected behavior

Playback to start. Works fine with series btw, so this is an issue with movie type only.

### Actual behavior

CTD

### Frequency

Always

### Did this work before?

Not sure

### Media details (optional)

Movie contents only. 
Discovered via AIOStreams Formatter.

### Logs (required for crash reports)

```shell
FATAL EXCEPTION: main
04-07 22:24:09.050  6072  6072 E AndroidRuntime: Process: com.nuvio.tv, PID: 6072
04-07 22:24:09.050  6072  6072 E AndroidRuntime: java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern : %
04-07 22:24:09.050  6072  6072 E AndroidRuntime: S
04-07 22:24:09.050  6072  6072 E AndroidRuntime: 	at java.net.URLDecoder.decode(URLDecoder.java:178)

or

FATAL EXCEPTION: main
Process: com.nuvio.tv, PID: 7797
java.lang.IllegalArgumentException: URLDecoder: Incomplete trailing escape (%) pattern
```

### Anything else? (optional)

_No response_

### PR DESCRIPTION
**Pull request by anikettuli**
## Summary

Bundle of 4 small uncovered bug fixes that share a defensive-handling-of-locale-and-user-input theme. None overlap with any open PR.

- `#1093` — Age rating falls back to US/GB for bare language codes like `"fr"`
- `#1184` — Player `S`/`E` episode labels are not localizable and inconsistently spaced
- `#1230` — Library alphabetical sort does not ignore leading `The`/`A`/`An`
- `#1275` — Player hard-crashes when a stream URL contains stray `%` characters

## PR type

- Bug fix

## Why

Four independent user-reported bugs, each with a clear reproducer and a localized fix. Bundled into one PR because they share a theme (defensive/correct handling of locale + user input) and because keeping them separate would fragment review for ~50 LoC total.

- **#1093:** Users on non-hyphenated locales (French `"fr"`, German `"de"`, Japanese `"ja"`, etc.) see American `PG-13`/`R` ratings instead of their local certification (French `TP`, etc.). Root cause: `preferredRegions()` uses `substringAfter("-", "")` to extract the region, gets an empty string for bare codes, and falls through to `[US, GB]`. The existing `selectBestLocalizedImagePath` on line 889 of the same file already solved this pattern with a `DEFAULT_LANGUAGE_REGIONS` fallback.
- **#1184:** Player season/episode labels are hardcoded as `"S${s}E${e}"` across the player UI — untranslatable and inconsistently spaced (`StreamSourcesSidePanel` used `"S01 E01"` while everything else used `"S01E01"`).
- **#1230:** Library alphabetical sort puts "The Walking Dead" under T instead of W, creating a giant "The" sub-bucket that's annoying to scroll.
- **#1275:** Movies whose stream metadata contains stray `%` (common with AIOStreams Formatter output) hard-crash the app on player launch via `URLDecoder: Illegal hex characters in escape (%) pattern`.

## Policy check

- [x] This PR is not cosmetic-only, unless it is a translation PR.
- [x] This PR does not add a new major feature without prior approval.
- [x] This PR is small in scope and focused on one problem.
- [x] If this is a larger or directional change, I linked the **approved** feature request issue below.

## Testing

**Automated:**
- `./gradlew :app:compileDebugKotlin` passes clean (Windows, AGP as configured). Verified both before and after the merge with `origin/dev`.
- Unit test task (`compileDebugUnitTestKotlin`) fails on `StreamTest.kt:38` (`Unresolved reference 'getStreamUrls'`) — pre-existing on the branch base, unrelated to this PR. Confirmed by stashing my changes and re-running against `b01b03d5`.

**Manual (please verify during review — I do not have a TV test device):**
- Set device locale to French (no region) → open a film with a known French certification → age badge should show French rating (`TP`/`12`), not US `PG-13`
- Play a series episode → verify `S01E02` shows consistently in: play/pause overlay, Sources side panel, Episodes side panel, Next Episode card, Modern Home hero, and Continue Watching cards
- Sort Library alphabetically → "The Walking Dead" sorts under W, not T
- Play a stream whose metadata contains `%` (e.g. AIOStreams-formatted source with `%` in the description) → player starts instead of crashing

## Screenshots / Video (UI changes only)

No new UI. Spacing of existing S/E labels is now consistently `S01E02` (padded, no space) across every visible player surface.

## Breaking changes

None.

- `WatchProgress.episodeDisplayString` property was removed — it had no remaining consumers after this PR's UI updates, and leaving the un-padded `"S${s}E${e}"` getter in place would invite regressing the unified format.
- `season_episode_format` is a new string resource. Translations for it will flow through the normal localization pipeline; no translation PR is bundled here.

## Linked issues

Fixes #1093
Fixes #1184
Fixes #1230
Fixes #1275

### CODE REVIEW

File: app/src/main/java/com/nuvio/tv/ui/screens/player/EpisodesSidePanel.kt [hunk 1]
```diff
@@ -469,7 +469,7 @@ private fun EpisodeItem(
         val s = episode.season
         val e = episode.episode
         if (s != null && e != null) {
-            "S${s.toString().padStart(2, '0')}E${e.toString().padStart(2, '0')}"
+            context.getString(R.string.season_episode_format, s, e)
```
Comment (skoruppa) [inline app/src/main/java/com/nuvio/tv/ui/screens/player/EpisodesSidePanel.kt:472]: There are more places where we have sXeX string. Hero content in modern home for CW and CW items

**Comment by anikettuli** [comment]
Pushed follow-up commit extending `#1184` coverage to the remaining user-visible S/E sites that were missing in the initial bundle:

- `ModernHomeModels.kt` — hero `episodeCode` for both `InProgress` and `NextUp` CW entries
- `ModernHomeModels.kt` — carousel `subtitle` for both branches of CW items
- `ContinueWatchingSection.ContinueWatchingCard` — `episodeStr` label

Also removed `WatchProgress.episodeDisplayString` now that every consumer uses the localized `season_episode_format` — keeping the dead getter would invite re-introducing the inconsistent un-padded `"S${s}E${e}"` format.

`./gradlew :app:compileDebugKotlin` passes clean.

**Comment by skoruppa** [comment]
@anikettuli can you resolve the conflict? I added support for "other" types and made a small conflict ;)

**Comment by anikettuli** [comment]
Resolved merge conflict with latest `dev`.

**Conflict:** `NextEpisodeCardOverlay.kt` — upstream PR #1464 ("Handle batch episode marking for 'other' type") added an `isOtherType` branch that renders just the title for "other"-type content where season/episode are synthetic.

**Resolution** preserves both behaviors:

```kotlin
val nextEpisodeLabel = if (nextEpisode.isOtherType) {
    nextEpisode.title
} else {
    val nextEpisodeCode = stringResource(
        R.string.season_episode_format,
        nextEpisode.season,
        nextEpisode.episode
    )
    "$nextEpisodeCode • ${nextEpisode.title}"
}
```

Audited the other S/E sites this PR touched (`PlayerScreen`, `PauseOverlay`, `StreamSourcesSidePanel`, `EpisodesSidePanel`) against the upstream versions — none were changed to handle "other" type, so no further adjustments needed. `strings.xml` auto-merged cleanly.

`./gradlew :app:compileDebugKotlin` passes clean against the merged tree.
